FROM pytorch/pytorch:2.5.1-cuda11.8-cudnn9-devel
ENV DEBIAN_FRONTEND=noninteractive

# Install Python and other dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    git-lfs \
    wget \
    curl \
    vim \
    unzip \
    pkg-config \
    software-properties-common \
    ibverbs-providers \
    ibverbs-utils \
    librdmacm-dev \
    rdmacm-utils \
    tzdata

RUN wget https://github.com/vllm-project/vllm/releases/download/v0.7.2/vllm-0.7.2+cu118-cp38-abi3-manylinux1_x86_64.whl && pip install vllm-0.7.2+cu118-cp38-abi3-manylinux1_x86_64.whl
